version: '3.8'

services:
  # Node.js + Hono + Prismaアプリケーション
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace
      - node_modules:/workspace/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://devuser:devpassword@db:5432/devdb
    ports:
      - "3000:3000"  # Honoアプリケーション
      - "5555:5555"  # Prisma Studio
    depends_on:
      - db
    command: sleep infinity  # DevContainerでは常駐させる

  # PostgreSQLデータベース
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=devdb
    ports:
      - "5432:5432"

volumes:
  postgres-data:
  pgadmin-data:
  node_modules:
